### ISSUE TITLE
大佬为什么你用V5S的模型在NX也能跑出100帧，我开20W6核功率用S模型才40多帧，用了tensorrt优化

### ISSUE THREAD

**Issue by broalantaps** [Spphire/YOLOarmor-2022final#1]
大佬为什么你用V5S的模型在NX也能跑出100帧，我开20W6核功率用S模型才40多帧，用了tensorrt优化

**Comment by Spphire** [comment]
可能的情况：
v5 6.0 比v5 5.0 的模型快
tensorrt我用的fp16加速
NX功率是8档，忘了啥性能了
我是单纯跑图片测试的帧率
我记得风扇还得手动激活到最大
